/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guoyonghui_ndktest_JNICalculator */

#ifndef _Included_com_guoyonghui_ndktest_JNICalculator
#define _Included_com_guoyonghui_ndktest_JNICalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guoyonghui_ndktest_JNICalculator
 * Method:    add
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_guoyonghui_ndktest_JNICalculator_add
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
